// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoL6ui0bMBWmNEcaoYUrIZudf59AXhe2M',
    appId: '1:9124368369:web:152f73c62403c1ea797e50',
    messagingSenderId: '9124368369',
    projectId: 'chat-app-57deb',
    authDomain: 'chat-app-57deb.firebaseapp.com',
    storageBucket: 'chat-app-57deb.appspot.com',
    measurementId: 'G-EEQ5RTYJKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdViTop8OiHJt60_bTxdXsTISAHJQG840',
    appId: '1:9124368369:android:46322b98b16c7016797e50',
    messagingSenderId: '9124368369',
    projectId: 'chat-app-57deb',
    storageBucket: 'chat-app-57deb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByeYc4ioZ5aSEvBRVeEKAWATGD-81xnUk',
    appId: '1:9124368369:ios:f098e84bd30e6320797e50',
    messagingSenderId: '9124368369',
    projectId: 'chat-app-57deb',
    storageBucket: 'chat-app-57deb.appspot.com',
    iosClientId: '9124368369-imr5j5qev3p9h1bgbg3q347n8dfn571m.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByeYc4ioZ5aSEvBRVeEKAWATGD-81xnUk',
    appId: '1:9124368369:ios:40281d5d6448fdd2797e50',
    messagingSenderId: '9124368369',
    projectId: 'chat-app-57deb',
    storageBucket: 'chat-app-57deb.appspot.com',
    iosClientId: '9124368369-k5n4oovimcfh9t61pu85n2oa0olqeuk5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
